### ISSUE TITLE
Quick time illustration

### ISSUE THREAD

**Issue by aertoria** [PattenUniversityOnlineEducation/TasksManagement#14]
Quick time illustration for use canvas

**Comment by yisionmumu** [comment]
Fix the video ratio to 480P, check the drive link to review.

https://drive.google.com/file/d/1lYiFEYbc3XfxpM5iORb4Vv9AaasXpj4u/view?usp=sharing

**Comment by cma00000** [comment]
https://pattenuniversityonlineeducation.github.io/student-instruction/

**Comment by yisionmumu** [comment]
<img width="876" alt="Screen Shot 2020-03-25 at 18 27 35" src="https://user-images.githubusercontent.com/60370016/77600883-6bd62e00-6ec6-11ea-8956-a40aa2fe1a47.png">
