### ISSUE TITLE
615. 635 Content Gen, Video Process.

### ISSUE THREAD

**Issue by cma00000** [PattenUniversityOnlineEducation/TasksManagement#19]

**Comment by cma00000** [comment]
615:
Xibin: 视频 unit1~4. course bank内容到excel
Yision: 视频/图片以及pdf上传阿里云，重新link到excel,  quiz stylish.

635:
Xibin: course bank内容到excel, 视频unit 1~4. 5~8(在做). 全部视频上传阿里云
Yision: course home, intro, review. Pdf 分页 reading part(在做)

**Comment by yisionmumu** [comment]
MBA615:
Video, images and PDF upload to Ali Cloud，Relink to the excel, Quiz stylish.
Course Home, Intro, Review. **Finished**

MBA635:
Course Home, Intro, Review. PDF with  Reading Part (**Processing**)

**Comment by cma00000** [comment]
工作流程：
https://github.com/PattenUniversityOnlineEducation/TasksManagement/wiki

**Comment by yisionmumu** [comment]
MBA635:
Video, images and PDF upload to Ali Cloud，Relink to the excel, Quiz stylish.
Course Home, Intro, Review, PDF with Reading Pages renew to Canvas. (**Finished**)
