### ISSUE TITLE
Discussion clean up, add demo discussion 

### ISSUE THREAD

**Issue by aertoria** [PattenUniversityOnlineEducation/TasksManagement#20]
What Do You Think?

If you are employed, have you observed any strategic or operational management decisions? What impact did these decisions have on employees, customers and/or suppliers? Post your ideas to the discussion board along with any discussion questions you would like to raise among your classmates.

**Comment by cma00000** [comment]
https://pattenuniversityonlineeducation.github.io/student-instruction/
