### ISSUE TITLE
600 content missing

### ISSUE THREAD

**Issue by aertoria** [PattenUniversityOnlineEducation/TasksManagement#23]
legends: unit1 , object2, missing Reading. -> u1o2 m-r

EMBA 600 issue:

u1o2 m link
u2o2 video issue
u3o1 m r
u4o1 m r
u4o2 m r
u5o2 m r
u5o3 m r
u6o1 m v
u6o3 m 
06o3 wrong

**Comment by cma00000** [comment]
Missing:
U3O1 part3 Reading
U3O2 part4 Reading
U4O1 part3 Reading
U4O3 part1 Reading
U4O3 part4 Reading
U5O2 part1 Reading
U5O2 part3 Reading
U5O3 part1 Reading
U6O1 part2 video 
U6O2 part1 Reading
U6O2 part2 Reading
U6O2 part3 External Page
U6O2 part4 Reading
U6O3 part1 Reading
U7O1 part2 video 
U7O2 part1 Reading
U7O3 part1 Reading
U8O3 part1 Reading

**Comment by cma00000** [comment]
Xibin: check missing part and update content in excel.
Cheng: rerun the missing pages

**Comment by cma00000** [comment]
新版旧版阅读材料对不上

**Comment by cma00000** [comment]
Xibin: 查找缺失，补充excel
Cheng: 内容在生成，课程最终版备份在google drive
