### ISSUE TITLE
Exercise link

### ISSUE THREAD

**Issue by aertoria** [PattenUniversityOnlineEducation/TasksManagement#24]
home work. upload, link

**Comment by aertoria** [comment]
Title: Ethanwang_EMBA600_homework_unit1_Ex1

xxxxxxxx

**Comment by cma00000** [comment]
Create a github page to include illustration video, submission instruction, discussion demo and so on.

**Comment by cma00000** [comment]
https://pattenuniversityonlineeducation.github.io/student-instruction/
