### ISSUE TITLE
BUS220 course gen

### ISSUE THREAD

**Issue by cma00000** [PattenUniversityOnlineEducation/TasksManagement#30]

**Comment by cma00000** [comment]
Xibin: all reading material, pdf processing, pdf link update.
Cheng: unit1~5 video processing. Update video link in excel.

**Comment by yisionmumu** [comment]
Yision: BUS200 Review Exercise, Course Home, Course Introduction to the Canvas. **Finished**

**Comment by yisionmumu** [comment]
Yision: Unit6~8 Video Processing. Update video link in excel. **Finished**

**Comment by cma00000** [comment]
220 content gen, paste, review.
